apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: rover
  name: rover
spec:
  containers:
  - image: docker.io/jpm/rover:latest
    imagePullPolicy: Never
    name: rover
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
