apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: rover
  name: rover
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: rover
  type: NodePort
status:
  loadBalancer: {}
